from typing import TypedDict

class RAGState(TypedDict):
    """
    Represents the state passed between nodes in a LangGraph-based RAG pipeline.

    Fields:
    - question: The full input question (possibly including context).
    - response: The agent's response to the question.

    This is used to enforce structure and type-checking across LangGraph nodes.
    """
    question: str       # User's input question or prompt
    response: str       # Answer generated by the agent
